### Crear un fichero

In [2]:
import numpy as np

In [2]:
""" Después de tartar los datos, limpiar los datos, dejar como nos gusta para guardar en nuestro disco duro."""
# Soponendo que queremos guardar esta matriz f

data = np.random.randint(0,100,size=(8,9), dtype=np.int32)

print(data)

[[12 46 85 37 63  8 79 96 36]
 [73 49 18 25 75 22 73 83 51]
 [49 92 12 40 25 14 90 43 20]
 [69 68 22 82 99 68 40 88 61]
 [42 58 52 93 18 30  0 53 87]
 [65 84 21 27 81  4 32 92 95]
 [57 17 83 26 75 49 83 41 40]
 [19 17 72 60 10 56 80 76 98]]


##### Guardar en CSV (coma separate values)
Guardar matriz en un fichero en que los datos son separados por coma

In [3]:
# Guardar el array f en un csv
""" sintaxi con 3 parametros: np.savetxt('nombre_archivo, variable_que_quiero_guardar, delimiter=',')
Por defecto es utilizado la coma, pero hay casos que no funciona pues,
pueden ser como separadores decimales y por eso es mejor punto y coma """

np.savetxt('file_data.csv', data, delimiter=';', fmt='%d')


##### Cargar el contenido del csv


In [6]:
# Cargar (importar) el contenido del csv en un array llamado file_data

file_data = np.loadtxt('file_data.csv', delimiter=';', dtype=np.int32)
print(file_data)

[[12 46 85 37 63  8 79 96 36]
 [73 49 18 25 75 22 73 83 51]
 [49 92 12 40 25 14 90 43 20]
 [69 68 22 82 99 68 40 88 61]
 [42 58 52 93 18 30  0 53 87]
 [65 84 21 27 81  4 32 92 95]
 [57 17 83 26 75 49 83 41 40]
 [19 17 72 60 10 56 80 76 98]]


##### Máscaras Booleanas
Nos desvuelve según condicionales, o sea, funciona como un filter de los datos.

In [7]:
# Podemos generar una máscara booleana para filtrar los datos
file_data > 75

array([[False, False,  True, False, False, False,  True,  True, False],
       [False, False, False, False, False, False, False,  True, False],
       [False,  True, False, False, False, False,  True, False, False],
       [False, False, False,  True,  True, False, False,  True, False],
       [False, False, False,  True, False, False, False, False,  True],
       [False,  True, False, False,  True, False, False,  True,  True],
       [False, False,  True, False, False, False,  True, False, False],
       [False, False, False, False, False, False,  True,  True,  True]])

In [10]:
# Esta máscara se puede aplicar a cualquier array
result = file_data[file_data>75]
print(result)
print("Shape:",result.shape)

[85 79 96 83 92 90 82 99 88 93 87 84 81 92 95 83 83 80 76 98]
Shape: (20,)


In [15]:
mayores_50 = file_data > 50

print(file_data[mayores_50])

[85 63 79 96 73 75 73 83 51 92 90 69 68 82 99 68 88 61 58 52 93 53 87 65
 84 81 92 95 57 83 75 83 72 60 56 80 76 98]


In [29]:
# Genera una lista de edades aleatorias
edades = np.random.randint(0,65,size=6)
# Personas
personas = np.array(['Juan', 'Ana', 'Pedro', 'Luis', 'María', 'Pablo'])

print(edades)
print(personas)

# Mayores de 18 años
mayores_18 = edades > 18
print(mayores_18)


[16 50 15 33 18  5]
['Juan' 'Ana' 'Pedro' 'Luis' 'María' 'Pablo']
[False  True False  True False False]


In [30]:
# Aplicar la máscara a la lista de personas
personas_mayores_18 = personas[mayores_18]
print(personas_mayores_18)

['Ana' 'Luis']


##### Any 
Si al menos hay algun dato que cumple la condición

In [32]:
# También podemos ver si alguno de los elementos cumple una condición
print(file_data)
print("\nHay al menos un dato que cumple esta condicion:", np.any(file_data > 75))

[[12 46 85 37 63  8 79 96 36]
 [73 49 18 25 75 22 73 83 51]
 [49 92 12 40 25 14 90 43 20]
 [69 68 22 82 99 68 40 88 61]
 [42 58 52 93 18 30  0 53 87]
 [65 84 21 27 81  4 32 92 95]
 [57 17 83 26 75 49 83 41 40]
 [19 17 72 60 10 56 80 76 98]]

Hay al menos un dato que cumple esta condicion: True


In [37]:
# Any indicando el axis=0 (columnas)
# Devuelve un booleano de tamaño igual al nº de columnas
column_mayores_80 = np.any(file_data > 80, axis=0)
column_mayores_90 = np.any(file_data > 90, axis=0)
print("Mayores que 80:",column_mayores_80)
print("Mayores que 90:", column_mayores_90)

Mayores que 80: [False  True  True  True  True False  True  True  True]
Mayores que 90: [False  True False  True  True False False  True  True]


In [39]:
# Me imprime solamente las columnas que es True, que hay mayores de 80.
file_data[:,column_mayores_80]

array([[46, 85, 37, 63, 79, 96, 36],
       [49, 18, 25, 75, 73, 83, 51],
       [92, 12, 40, 25, 90, 43, 20],
       [68, 22, 82, 99, 40, 88, 61],
       [58, 52, 93, 18,  0, 53, 87],
       [84, 21, 27, 81, 32, 92, 95],
       [17, 83, 26, 75, 83, 41, 40],
       [17, 72, 60, 10, 80, 76, 98]])

In [40]:
# Podemos hacer lo mismo pelo en las filas axis=1
filas_mayores_80 = np.any(file_data > 80, axis=1)
filas_mayores_90 = np.any(file_data > 90, axis=1)

file_data[filas_mayores_90,:]

array([[12, 46, 85, 37, 63,  8, 79, 96, 36],
       [49, 92, 12, 40, 25, 14, 90, 43, 20],
       [69, 68, 22, 82, 99, 68, 40, 88, 61],
       [42, 58, 52, 93, 18, 30,  0, 53, 87],
       [65, 84, 21, 27, 81,  4, 32, 92, 95],
       [19, 17, 72, 60, 10, 56, 80, 76, 98]])

In [43]:
# Filtrar los datos de las filas que tengan valores mayores que 80
f1 = file_data[filas_mayores_80,:]
#Sobre ese resultado filtrar las columnas que tengam valores mayores que 90
col_mayores_90 = np.any(f1>90, axis=0)
f1[:,col_mayores_90]

array([[46, 37, 63, 96, 36],
       [49, 25, 75, 83, 51],
       [92, 40, 25, 43, 20],
       [68, 82, 99, 88, 61],
       [58, 93, 18, 53, 87],
       [84, 27, 81, 92, 95],
       [17, 26, 75, 41, 40],
       [17, 60, 10, 76, 98]])

In [46]:
# Se puede anidar estas funciones para acotar un dato por ejemplo

mask = np.any( (file_data> 40) & (file_data < 60), axis=1)
print(mask)

#Seleccionar los datos que cumplen la condición
file_data[mask,:]

[ True  True  True False  True False  True  True]


array([[12, 46, 85, 37, 63,  8, 79, 96, 36],
       [73, 49, 18, 25, 75, 22, 73, 83, 51],
       [49, 92, 12, 40, 25, 14, 90, 43, 20],
       [42, 58, 52, 93, 18, 30,  0, 53, 87],
       [57, 17, 83, 26, 75, 49, 83, 41, 40],
       [19, 17, 72, 60, 10, 56, 80, 76, 98]])

Ejemplo

In [9]:
# DEfinimos una matriz en el que cada columna es un mes del año y cada fila es un departamento de mi empresa
departamentos = np.array(['Ventas', 'Marketing', 'RRHH', 'Compras', 'Producción'])

gastos = np.random.randint(0,10000, size = (5,12), dtype=np.int32)
print(gastos)

[[7147 6521 3103 5862 8085 5863 2037 9624 9394 3890   60 2399]
 [ 595 7716 5522 1617 5805 3804  651 7917 2316 7112 5435 9623]
 [4632 5201 1293 5753  721 3030 4223 1608 8548 5306 2357 7680]
 [8449  151 9172 4820 7909 7336 7108  906  243 9150 1600 4224]
 [7670 7400 3919 4235 6765 4092 6771 7436 8260 9180 9172 9277]]


In [10]:
# Conocer que departamentos gastan más de 5000€ en el mes de enero [rows,columns] = [empresa:mes]
gastos[:,0] > 5000
print(departamentos[gastos[:,0] > 5000])

['Ventas' 'Compras' 'Producción']
