# Python numpy

>> Numpy

Documentação : https://numpy.org/doc/stable/user/absolute_beginners.html#numpy-the-absolute-basics-for-beginners


>> Intalación

Insira o código abaixo no Anaconda Prompt:
<b>pip install numpy</b>
https://numpy.org/install/



>> Importación
https://numpy.org/doc/stable/user/absolute_beginners.html#how-to-import-numpy

## Qué es un array?
Tipos de arrays:
ndarrays -> significam arrays com N dimensões<br>

1-D array-> Possui apenas uma dimensão. Será comumente chamado de <b> vetor ou vector </b> <br>
2-D array -> Possui 2 dimensões. Será comumente chamado de <b> matriz ou matrix</b> <br>
3-D ou Mais array -> Possui 3 ou mais dimensões. Será comumente chamado de <b>tensor</b> 
                                     
https://numpy.org/doc/stable/reference/arrays.html#arrays

In [1]:
""" Importamos numpy como np, para facilitar y que no haga falta escribir siempre la palabra numpy y sí, np"""
import numpy as np


### Primeros pasos

### np.array() 
*Todos los valores del array deben ser del mismo tipo ( numeros, str...)


Array Vector: de una dimensión

In [14]:
# Para iniciar un array de numpy llamamos a la funcion np.array()
# todos los valores de array deben ser del mismo tipo
a = np.array([1,2,3,4,5]) 

print("array: a ", a)

print ("dimension de a: ", a.ndim)

array: a  [1 2 3 4 5]
dimension de a:  1


Array Matrix: de dos dimensiones

In [13]:
# Para inicializar un array de dimension 2 podemos pasar una lista de listas
b = np.array([
    [1,2,3],[4,5,6]
    ])
print(b)
print("Dimension de b:", b.ndim )


[[1 2 3]
 [4 5 6]]
Dimension de b: 2


Array de trés dimensiones: Tensor

In [16]:
# Podemos anidar mas listas para crear arrays de dim 3 o mas
c = np.array( [
    [
        [1,2,3], [4,5,6]
    ],
    [
        [1,2,3], [4,5,6]
    ]

] )
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [18]:
print("Dimensión de c:",c.ndim)

Dimensión de c: 3


Otro ejemploe de Array de 3 dimensiones: Tensor

In [19]:
#vamos a crear un array de 3 dimenensiones 
d=np.array ([
    [
    [1,4,7],
    [2,9,7],
    [1,3,0],
    [9,6,9]],
            
    [
    [2,3,4],
    [4,5,5],
    [1,2,2],
    [9,3,8]]
    ])


print(d)
print("Dimensión de d: ",d.ndim)


[[[1 4 7]
  [2 9 7]
  [1 3 0]
  [9 6 9]]

 [[2 3 4]
  [4 5 5]
  [1 2 2]
  [9 3 8]]]
Dimensión de d:  3


## shape
El shape de un array es una tupla que indica el tamaño de cada dimensión <br>

Imagen representativa de las dimensiones de array: 1D, 2D, 3D<br> 


<br><img src=https://aprendeconalf.es/docencia/python/manual/img/arrays.png>


In [27]:
#El shape de un array es una tupla que indica el tamaño de cada dimnsion
print ("Array a:", a)
print("Shape de a:", a.shape) # me va a pasar el numero de elementos del array 
print ("En la tupla, el primer elemento es la cantidad de elemento y la segudna es vacío, pues es solo de una dimensión")

print ("--------------")

print ("Array b:")
print (b)
print("hsape de b:", b.shape)
print ("Me devolve dos nº, la primera es la cantidad de filas y el otro nº es la cantidad de elemntos en cada fila ")

print ("--------------")
print ("Array c:")
print (c)
print("c:" , c.shape)
print ("Aqui es 3D: el primer nº es la cantidad de matrices, despues cantidad de filas y el último columnas")

Array a: [1 2 3 4 5]
Shape de a: (5,)
En la tupla, el primer elemento es la cantidad de elemento y la segudna es vacío, pues es solo de una dimensión
--------------
Array b:
[[1 2 3]
 [4 5 6]]
hsape de b: (2, 3)
Me devolve dos nº, la primera es la cantidad de filas y el otro nº es la cantidad de elemntos en cada fila 
--------------
Array c:
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
c: (2, 2, 3)
Aqui es 3D: el primer nº es la cantidad de matrices, despues cantidad de filas y el último columnas


In [29]:
print ("Array d")
print(d)
print("Dimensión:", d.ndim)
print("Shape:", d.shape)


Array d
[[[1 4 7]
  [2 9 7]
  [1 3 0]
  [9 6 9]]

 [[2 3 4]
  [4 5 5]
  [1 2 2]
  [9 3 8]]]
Dimensión: 3
Shape: (2, 4, 3)


In [31]:
e=np.array ([
    [
    [1,4,7],
    [2,9,7],
    [1,3,0],
    [9,6,9]],
            
    [
    [2,3,4],
    [4,5,5],
    [1,2,2],
    [9,3,8]
    ],

    [
    [2,3,4],
    [4,5,5],
    [1,2,2],
    [9,3,8]]

    ])

print("Array e")
print(e)
print("Dimensión de e:", e.ndim)
print("Shape de e:", e.shape)


Array e
[[[1 4 7]
  [2 9 7]
  [1 3 0]
  [9 6 9]]

 [[2 3 4]
  [4 5 5]
  [1 2 2]
  [9 3 8]]

 [[2 3 4]
  [4 5 5]
  [1 2 2]
  [9 3 8]]]
Dimensión de e: 3
Shape de e: (3, 4, 3)


### Obtener el tipo de dato de un array 
x.dtype

In [26]:
a.dtype

dtype('int32')

Bits y Bytes

In [ ]:
# Representación de un byte en binario -> 1010
""" 
Bit = Binary Digit (zero o uno)
8 bits = 1 Byte (tamaño o capacidad de armacenamiento)
"""

# El tipo int16 puede representar un nº entero de 16 bits (ocuapación de la memória equivalente a 2 bytes) (-32.768 a 32.767)
# El tipo int32 puede representar un nº entero de 32 bits (ocuapación de la memória equivalente a 4 bytes) (-2.147.648 a 2.147.483.647)
# El tipo int64 puede representar un nº entero de 64 bits (ocuapación de la memória equivalente a 8 bytes) (-9.233.372.036.854.775.808 a 92.23.372.036.854.775.807)

#El tipo float32 puede representar un nº real de 32 bits (ocuapación de la memória equivalente a 4 bytes) (-3.40282335e+38 a 3.40282335e+38)
#El tipo float64 puede representar un nº real de 64 bits (ocuapación de la memória equivalente a 8 bytes) (-1.7976931348623157e+308 a 1.7976931348623157e+308)

In [46]:
""" Define un array de dim 2 y de tipo int16 """

arr16 = np.array([[1,2,3],[4,5,6]], dtype=np.int16)
print ("imprimir matrix arr16:\n", arr16)
print("tipo de la matrix:", arr16.dtype)


imprimir matrix arr16:
 [[1 2 3]
 [4 5 6]]
tipo de la matrix: int16


Ejemplo con array de int16 y con un nº que no sea capaz de manejar

In [35]:
""" Un situación en que int16 no soportaría... nº mayores de 32.767. Resulta un error con valor negativo.
Es decir, el tipo de dato no es capaz de manejar valores fuera de su rango (32.768) por lo que se produce un overflow e introduce basura """

b16 = np.array([[1,2,3],[4,5,64000]], dtype=np.int16)
print(b16)

[[    1     2     3]
 [    4     5 -1536]]


Ejemplo de array con int32

In [36]:
""" Igual de la anterior pero con int32, en que soporta nº 64000..no nos dá error"""
c16 = np.array([[1,2,3],[4,5,64000]], dtype=np.int32)
print(c16)

[[    1     2     3]
 [    4     5 64000]]


Convertir el type de array: 
<br> astype

In [40]:
# Redefinir el tipo de un array
""" Convertir el array arr16 a tipo int32, sin modificar el objeto"""

arr32 = arr16.astype(np.int32) # Transformo para int32 sin alterar el objeto

print("arr16 type:", arr16.dtype)
print(arr16)
print ("arr32 type:", arr32.dtype)
print(arr32)




arr16 type: int16
[[1 2 3]
 [4 5 6]]
arr32 type: int32
[[1 2 3]
 [4 5 6]]


Saber cuanto ocupa en memoria un array de int16 (2 bytes)

<br>x.itemsize


In [42]:
print("El arr16 ocupa un espacio en la memória de:" ,arr16.itemsize, "bytes")

El arr16 ocupa un espacio en la memória de: 2 bytes


Número de elementos que tiene el array

<br> size =      nº de elementos

In [44]:
print("Utilizando size para saber el nº de elementos de arr16:", arr16.size)

Utilizando size para saber el nº de elementos de arr16: 6


Tamaño total size * itemsize

In [45]:
print("Tamaño total del array arr16:", arr16.size * arr16.itemsize)

Tamaño total del array arr16: 12


### Memória

Memória con array de int16

In [55]:
print('Array 16:\n', arr16,"\n")
print('Elementos array arr16:' , arr16.size, 'elementos')
print('Tamaño de cada elemento del array arr16:', arr16.itemsize, 'bytes')
print("Tamaño total del array arr16:", arr16.size * arr16.itemsize, 'bytes')

Array 16:
 [[1 2 3]
 [4 5 6]] 

Elementos array arr16: 6 elementos
Tamaño de cada elemento del array arr16: 2 bytes
Tamaño total del array arr16: 12 bytes


In [56]:
print('Array 32:\n', arr32,"\n")
print('Elementos array arr32:' , arr32.size, 'elementos')
print('Tamaño de cada elemento del array arr32:', arr32.itemsize, 'bytes')
print("Tamaño total del array arr32:", arr32.size * arr32.itemsize, 'bytes')

Array 32:
 [[1 2 3]
 [4 5 6]] 

Elementos array arr32: 6 elementos
Tamaño de cada elemento del array arr32: 4 bytes
Tamaño total del array arr32: 24 bytes


### Otra forma de inicializar un array:

Range

In [ ]:
ejemplo1 = list(range(10))
print("Imprimir una lista con range:", ejemplo1)

print("\nImprimir cada elemento de la lista:")
for i in range (10):
    print(i)

In [66]:
"""Inicializar array con range. El array debe tener 10 elementos"""

a0 = np.array(range(10))
print(a0)

[0 1 2 3 4 5 6 7 8 9]


In [67]:
a1 = np.array(range(10,20))
print(a1)

[10 11 12 13 14 15 16 17 18 19]


In [69]:
a2 = np.array(range(10,25,5))
print(a2)

[10 15 20]


Numpy: arange<br> 
<br> (solo se puede hacer c solo una lista)

In [70]:
''' Inicializar un array con arange. Desde 10 hasta 20 con paso 2 '''

b = np.arange(10,20,2)
print(b)

[10 12 14 16 18]


Ejercicios

In [76]:
'''
Define el array 'a' del 1 al 10
'''
a = np.arange(1,11)
print(a)
'''
Imprime la dimension del array y el shape
'''

print('Dimension (1d, 2d o 3d?):', a.ndim)
print('formato (shape):', a.shape)

[ 1  2  3  4  5  6  7  8  9 10]
Dimension (1d, 2d o 3d?): 1
formato (shape): (10,)


In [82]:
''' 
Define de un array 'b' de dimensiones 2x3 a partir de listas anidadas
'''

b = np.array([[1,2,3],[4,5,6]])
print("array b:\n", b)
print("\n Shape:", b.shape)

array b:
 [[1 2 3]
 [4 5 6]]

 Shape: (2, 3)


In [88]:
'''
Define un array 'c'  de dim 2x2x3 a partir de una lista de listas anidadas 
'''
c = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])


print("Array c:\n", c, "\n\nShape de c:\n", c.shape)

'''
Imprime el número total de elementos del array y el shape
'''

print("\nElementos con Size:", c.size)

Array c:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 

Shape de c:
 (2, 2, 3)

Elementos con Size: 12


## Accediendo y Modificando elementos de un array

In [90]:
# Array f de 2x5
f = np.array([[1,2,3,8,7],[4,5,6,2,9]])
print(f)

[[1 2 3 8 7]
 [4 5 6 2 9]]


Obtener un elemento de un array

index: [row,column]

In [92]:
# Obtener un elemento concreto de un array [rows,columns]

# Obtener el elemento 6 del array f
print("elemento 6:", f[1,2])

# Obtener el elemento 8 del array f
print("elemento 8:", f[0,3])


elemento 6: 6
elemento 8: 8


Obtener una fila completa de un array

In [95]:
# Para obtener una fila completa utilizamos la notación ':' como en la listas
f = np.array([[1,2,3,8,7],[4,5,6,2,9]])
print(f)

f[1,:]



[[1 2 3 8 7]
 [4 5 6 2 9]]


array([4, 5, 6, 2, 9])

Obtener una columna completa de un array

In [103]:
# define un array 'f' de dimensiones 4x5
f = np.array([[1,2,3,8,7],[4,5,6,2,9],[1,2,3,8,7],[4,5,6,2,9]])
print(f)
print("\nshape",f.shape)

# Obtener la columna 3 de array f
print("\nColuman 3:", f[:,2])



[[1 2 3 8 7]
 [4 5 6 2 9]
 [1 2 3 8 7]
 [4 5 6 2 9]]

shape (4, 5)

Columan 3: [3 6 3 6]


Otras formas de acceder a los elementos de un array

[inicio: final: paso]

In [106]:
# Para acceder de una forma un poco más avanzada se utiliza [inicio: final: paso]
f = np.array([[1,2,3,8,7],[4,5,6,2,9],[1,2,3,8,7],[4,5,6,2,9]])
print("Array f:\n", f)

#De la primera fila, del elemento 1 al 4 con paso 2
print("\nDe la primera fila, del elemento 1 al 4 con paso 2\n","f[0,1:4:2]")
f[0,1:4:2]

Array f:
 [[1 2 3 8 7]
 [4 5 6 2 9]
 [1 2 3 8 7]
 [4 5 6 2 9]]

De la primera fila, del elemento 1 al 4 con paso 2
 f[0,1:4:2]


array([2, 8])

Obtener las filas pares 

arr = [filas, columnas]

In [108]:
# Para acceder de una forma un poco más avanzada se utiliza [inicio: final: paso, inicio: final: paso]
f = np.array([[1,2,3,8,7],[4,5,6,2,9],[1,2,3,8,7],[4,5,6,2,9]])
print("Array f:\n", f)

#Obtener las filas pares: todas las filas con paso 2 [::2] y todas las columnas [:]
print("\nDe la primera fila, del elemento 1 al 4 con paso 2\n","f[0,1:4:2]")
f[::2,:]

Array f:
 [[1 2 3 8 7]
 [4 5 6 2 9]
 [1 2 3 8 7]
 [4 5 6 2 9]]

De la primera fila, del elemento 1 al 4 con paso 2
 f[0,1:4:2]


array([[1, 2, 3, 8, 7],
       [1, 2, 3, 8, 7]])

Invertir orden de las filas

In [112]:
# Recorrer el array con paso negativo

f_invertido= f[::-1,:]
print(f_invertido)

[[4 5 6 2 9]
 [1 2 3 8 7]
 [4 5 6 2 9]
 [1 2 3 8 7]]


In [117]:
# Definir un array de 3x3x2

g = np.array([
[[10,20],[30,40],[50,60]],
[[11,21],[31,41],[51,61]],
[[12,22],[32,42],[52,62]]
])

print(g)
print(g.shape)


[[[10 20]
  [30 40]
  [50 60]]

 [[11 21]
  [31 41]
  [51 61]]

 [[12 22]
  [32 42]
  [52 62]]]
(3, 3, 2)


In [123]:
#Acceder elemento 41
print(g[1,1,1])

# Acceder 52
print(g[2,2,0])

#Acceder una fila entera: la fila 2 del elemento 1
print("fila enetera:", g[2,2,:])



41
52
fila enetera: [52 62]


Actualizar un elemento de un array

In [2]:
# Podemos actualizar la información de un array igual que seleccionando un elemento e igualandolo con un nuevo valor
# Para este ejemplo vamos a utilizar el array 'h' de 3x3x2

h = np.array([
[[10,20],[30,40],[50,60]],
[[11,21],[31,41],[51,61]],
[[12,22],[32,42],[52,62]]
])

print(h,'\n')

#Cambiar el elemento 50 a 500
print("Cambio:\n")
h[0,2,0] = 500
print(h)

[[[10 20]
  [30 40]
  [50 60]]

 [[11 21]
  [31 41]
  [51 61]]

 [[12 22]
  [32 42]
  [52 62]]] 

Cambio:

[[[ 10  20]
  [ 30  40]
  [500  60]]

 [[ 11  21]
  [ 31  41]
  [ 51  61]]

 [[ 12  22]
  [ 32  42]
  [ 52  62]]]


Alterando una fila completa

In [140]:
i = np.array([[[1,2,3],[4,5,6],[7,8,9]],
[[10,20,30],[40,50,60],[70,80,90]]])

print("original\n", i)

#Cambilar la fila [10,20,30] a ceros
i[1,0,:] = 0
print("\n cambio\n",i)

#Cambilar la fila [10,20,30] a 90,100,110
i[1,0,:] = [90,100,110]
print("\n cambio 2\n",i)

original
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]]

 cambio
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[ 0  0  0]
  [40 50 60]
  [70 80 90]]]

 cambio 2
 [[[  1   2   3]
  [  4   5   6]
  [  7   8   9]]

 [[ 90 100 110]
  [ 40  50  60]
  [ 70  80  90]]]


Alterar una columna a 0s

In [142]:
j = np.array([[[1,2,3],[4,5,6],[7,8,9]],
[[10,20,30],[40,50,60],[70,80,90]]])

print("Original:\n", j, "\n")
#Cambiar la columna [20,50,80] [20,50,80]por ceros

j[:,:,1]=0
print("cambio:\n",j)


Original:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]] 

cambio:
 [[[ 1  0  3]
  [ 4  0  6]
  [ 7  0  9]]

 [[10  0 30]
  [40  0 60]
  [70  0 90]]]


Columnas con valores diferentes

In [144]:
k = np.array([[[1,2,3],[4,5,6],[7,8,9]],
[[10,20,30],[40,50,60],[70,80,90]]])

print("Original:\n", k, "\n")
#Cambiar las ultimas columnas por valores diferentes

k[:,:,-1]= [1,2,3],[4,5,6]
print("cambio:\n",k)

Original:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]] 

cambio:
 [[[ 1  2  1]
  [ 4  5  2]
  [ 7  8  3]]

 [[10 20  4]
  [40 50  5]
  [70 80  6]]]


Ejercicios

In [8]:
'''
Define un array 's' de tamaño 10 y selecciona el valor de la posición 5
'''
s = np.array([[1,2,3,8,7],[4,5,6,2,9]])
print(s)

print(s[0,4])



[[1 2 3 8 7]
 [4 5 6 2 9]]
7


In [11]:
'''
Sobre el array s, selecciona el valor 5
'''
print(s[1,1])

5


In [16]:
'''
Define el array 's' de tamaño 25 y selecciona los valores pares
'''

s = np.random.randint(0,50, size=(5,5))
print(s)

print("\nPares:", s[s%2==0])


[[24 12 36 38 38]
 [10 32 26 42  6]
 [20 16 13 25 10]
 [29 19 26 45  7]
 [39 12 33 39 11]]

Pares: [24 12 36 38 38 10 32 26 42  6 20 16 10 26 12]


In [19]:
'''
Define el array 's' de tamaño 25 y selecciona los valores impares
'''

s = np.random.randint(0,50, size=(5,5))
print(s)

print("\nImpares:", s[s%2!=0])

[[48 19  5 10 24]
 [ 3 46 35 44  7]
 [32 40 12 26 32]
 [33 37 13 22 27]
 [15 29 35 17 37]]

Impares: [19  5  3 35  7 33 37 13 27 15 29 35 17 37]


In [20]:
'''
Sobre el array s, selecciona el uĺltimo valor
'''
s[-1,-1]

37

In [26]:
"""
Define el array 's' de tamaño 20 e invierte el orden de los valores
"""
s = np.random.randint(20, size=(5,4))
print("Matriz original:\n", s)
#Obtener la matriz inversa
inversa = np.flip(s)
print("\nMatriz inversa:\n " ,inversa)

#invirtir con slicing
print("\ninvirtir con slicing:\n", s[::-1])


Matriz original:
 [[11  4  0 15]
 [10 16 19 18]
 [16  4  3 10]
 [ 9 13 15 10]
 [14 12  8  7]]

Matriz inversa:
  [[ 7  8 12 14]
 [10 15 13  9]
 [10  3  4 16]
 [18 19 16 10]
 [15  0  4 11]]

invirtir con slicing:
 [[14 12  8  7]
 [ 9 13 15 10]
 [16  4  3 10]
 [10 16 19 18]
 [11  4  0 15]]


In [31]:
'''
Define un array s2 multidimensional de tamaño 2x2 y selecciona el valor de la segunda fila y la segunda columna
'''
s2 = np.array([[5,4],[6,8]])
print(s2)

print(s2[1,1])



[[5 4]
 [6 8]]
8


In [36]:
'''
Define el array:
[
[[1, 2], [3, 4]]
[[5, 6], [7, 8]]
]
y selecciona el valor de la segunda dimension, primera fila, segunda columna
'''
t = np.array([
[[1, 2], [3, 4]],
[[5, 6], [7, 8]]])

print("Original:\n", t)
print(t[1,0,1])





Original:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
6


In [42]:
'''
Define un array s4 de tamaño 4x4x3 y establece los números centrales a 99
'''

s4 = np.random.randint(0,100,size=(4,4,3) )


s4[:,:,1]=99
print("Modificada:\n",s4 )

Modificada:
 [[[66 99 92]
  [23 99 26]
  [47 99 50]
  [50 99 53]]

 [[23 99 97]
  [79 99 77]
  [44 99 36]
  [32 99  1]]

 [[ 8 99 19]
  [11 99 56]
  [41 99 47]
  [32 99 89]]

 [[56 99 45]
  [17 99 24]
  [42 99 27]
  [14 99 45]]]


In [45]:
'''
Define un array s4 de tamaño 4x4x3 y establece los números centrales a (0,1), (2,3), (4,5), (6,7)
'''
s4 = np.random.randint(0,100,size=(4,4,3) )
s4[0,1:3,1]=(0,1)
s4[1,1:3,1]=(2,3)
s4[2,1:3,1]=(4,5)
s4[3,1:3,1]=(6,7)
s4

array([[[ 0,  3, 47],
        [90,  0, 81],
        [44,  1, 54],
        [48,  4,  3]],

       [[ 5, 18, 82],
        [21,  2,  5],
        [34,  3, 86],
        [31, 10, 83]],

       [[61, 15, 20],
        [44,  4, 91],
        [ 3,  5, 38],
        [85, 60, 28]],

       [[49, 96, 74],
        [85,  6, 88],
        [ 7,  7, 41],
        [91,  1, 62]]])

## Inicializando diferentes tipos de arrays

Matriz de ceros

In [146]:
# Definir una matriz completa de 0 de tamaño 5x3

np.zeros((5,3))
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [149]:
# Definir una matriz completa de 0 de tipo int32 de tamaño 5x3

arr_ceros = np.zeros((5,3), dtype=np.int32)
print(arr_ceros)
print(arr_ceros.dtype)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
int32


In [173]:
# Podemos generar una matriz de zeros con un shape (2,3,4)
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

Determinar una matriz por una de tamaño ya predeterminada la transformando en 0

In [159]:
l = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(l.dtype)
print("Original:\n",l,"\n")


#Definir una matriz de 0 del shape de l 
print("np.zeros()")
zeros1 = np.zeros(l.shape)
print(zeros1.dtype)
print(zeros1, '\n')


#Otra forma de hacerlo es con zeros_like() copiando el shape de int32
print("np.zeros_like():")
zeros2 = np.zeros_like(l)
print(zeros2.dtype)
print(zeros2)


int32
Original:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]] 

np.zeros()
float64
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

np.zeros_like():
int32
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


Matriz de unos

In [162]:
np.ones((5,3), dtype=np.int32) #Definir una matriz de unos de tamaño 5x3

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [163]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [214]:
np.empty((5,3)) #numeros aleatorios, no se puede hacer matriz sin nada

array([[27.24188834, 30.03831457, 28.14523697],
       [50.12185137, 43.40113009, 60.40099294],
       [16.4236797 , 34.78012122, 73.1431462 ],
       [25.80534267, 64.82480389,  6.96533055],
       [17.70630521,  3.83873574, 82.39881108]])

In [224]:
# Entre numero de 0 y 50, 20 numeros sin el ultimo nº y el retstep muestra el paso

array_linear = np.linspace(0 , 50 , num = 20 , endpoint = False, retstep= True)
print(array_linear)


(array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5, 25. ,
       27.5, 30. , 32.5, 35. , 37.5, 40. , 42.5, 45. , 47.5]), 2.5)


Matriz de valores concretos

np.full()

In [164]:
np.full((5,3),50)

array([[50, 50, 50],
       [50, 50, 50],
       [50, 50, 50],
       [50, 50, 50],
       [50, 50, 50]])

In [170]:
#Añadir punto despues del numero para que sea flotante o si no... 50, dtype=np.float64
p = np.full((5,3),50.)
print(p)
print("\n tipo:", p.dtype)

[[50. 50. 50.]
 [50. 50. 50.]
 [50. 50. 50.]
 [50. 50. 50.]
 [50. 50. 50.]]

 tipo: float64


Matriz de valores concretos (full like)

In [172]:
# Define una matriz como p pero con valores de 75
np.full_like(p,75)

array([[75., 75., 75.],
       [75., 75., 75.],
       [75., 75., 75.],
       [75., 75., 75.],
       [75., 75., 75.]])

Matriz de números aleatorios

In [228]:
# Hashtag Programação
from numpy.random import default_rng

rng = default_rng()

aleatorio = rng.integers(10, size = (2,4))

print(aleatorio)


[[7 7 3 4]
 [3 8 4 1]]


In [174]:
# Atencion! Cuando creamos una matriz de números aleatórios No se pasa el shape por parametro
# Define una matriz de tamaño 5x3 con valores aleatorios
np.random.rand(5,3)

array([[0.19385405, 0.59033529, 0.27707841],
       [0.25105109, 0.96827277, 0.14380196],
       [0.19894874, 0.17496867, 0.97364612],
       [0.58539871, 0.84461986, 0.12769248],
       [0.19712764, 0.69670381, 0.4658182 ]])

In [178]:
# Definir una matriz de 5x3 con valores aleatorios mayores que uno.
np.random.rand(5,3)*100



array([[27.24188834, 30.03831457, 28.14523697],
       [50.12185137, 43.40113009, 60.40099294],
       [16.4236797 , 34.78012122, 73.1431462 ],
       [25.80534267, 64.82480389,  6.96533055],
       [17.70630521,  3.83873574, 82.39881108]])

Randon de Numpy y no de Python

In [176]:
# Definir una matriz de 5x3 con valores entre 0 ,100 utilizando randint (randon de nºs enteros)
np.random.randint(0,100,(5,3))
# np.random.randint(0,100,size=(5,3))


array([[33,  4, 94],
       [47, 83, 74],
       [36, 83, 84],
       [78, 88, 63],
       [56, 59, 99]])

Matriz identidad

In [205]:
# Define la matriz identidad (cuadrado) de tamaño 5x5
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [204]:
#La matriz identidad se puede definir con la función 'identity'
print(np.identity(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Ejercicios

In [50]:
'''
Define el array z de dim 1 completo de ceros
'''
z = np.random.randint(10, size=(1,5))
print(z)
print(np.zeros(z.shape))

[[1 7 9 5 4]]
[[0. 0. 0. 0. 0.]]


In [66]:
'''
Define un array z de dim 8x8 completo de ceros
'''
z = np.zeros((8,8))
z

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [68]:
'''
Define el array 'z' completo de ceros de n dim
'''
z1 = z.reshape(4,4,4)
np.zeros(z1.shape)



array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [71]:
'''
Define el array 'd' completo de unos de n dim
'''
d = np.ones((2,4,3))

In [74]:
'''
Define un array como el que se muestra a continuación:
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
'''

x = np.zeros((8,8))
x[1:-1,1:-1]=1
x



array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [85]:
'''
Define un array 'g' con un range de 0 a 10 de dim 2
'''
g = np.array(range(10))
g1 = g.reshape(2,5)
print(g1)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [90]:
'''
Define un array 'h' con un range de 0 a 100 con un paso de 5 y una dim difrente de 1
'''
h = np.array(range(0,100,5))
print(h.size)

h1 = h.reshape(2,5,2)
h1


20


array([[[ 0,  5],
        [10, 15],
        [20, 25],
        [30, 35],
        [40, 45]],

       [[50, 55],
        [60, 65],
        [70, 75],
        [80, 85],
        [90, 95]]])

## Operaciones con arrays

Operaciones básicas:

Las operaciones basicas con arrays o matrices son "element wise".
Esto significa que se aplican a cada elemento de la matriz.

<br>sum() suma
<br>max() maximo
<br>min() minimo
<br>mean() media

In [181]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


suma

In [183]:
#Suma cada elelemento por el nº que damos
print(a + 2)

[3 4 5 6 7]


resta

In [184]:
print(a - 2)

[-1  0  1  2  3]


Multiplicación

In [185]:
print(a * 2)

[ 2  4  6  8 10]


División

In [186]:
print(a / 2)

[0.5 1.  1.5 2.  2.5]


Exponenciación

In [187]:
print(a ** 2)

[ 1  4  9 16 25]


In [188]:
b = np.array([10, 20, 30, 40, 50])
print(b)

[10 20 30 40 50]


Se puede sumar dos arrays solamente si es del mismo tamaño

In [189]:
print(a+b)

[11 22 33 44 55]


Ejercicios

In [193]:
'''
Define un array 'a' de tamaño 4 y un array 'b' de tamaño 4 completo de 1s. A contunuación suma los valores de ambos arrays y comprueba que los valores son correctos.
'''
a = np.random.randint(0,100, size=(4))
print(a)
b= np.ones((4))
print(b)
print(a+b)

[16 60  7 60]
[1. 1. 1. 1.]
[17. 61.  8. 61.]


In [95]:
'''
Define un array 'a' de tamaño 4 y un array 'b' de tamaño 4 completo de 1s.
A contunuación resta los valores de ambos arrays y comprueba que los valores son correctos.
'''
a = np.array([2,3,4,5])
b = np.ones((4))
print("a", a)
print("b", b)

print(a-b)

a [2 3 4 5]
b [1. 1. 1. 1.]
[1. 2. 3. 4.]


In [96]:
'''
Define un array 'a' de tamaño 4 y un array 'b' de tamaño 4 completo de 2s.
A contunuación multiplica o divide los valores de ambos arrays y comprueba que los valores son correctos.
'''
a = np.full((4),2)
b = np.full((4),2)
print(a*b)

[4 4 4 4]


### Álgebra lineal

numpy py permite realizar operaciones matriciales como por elemplo:
- determinante: np.linalg.det()
- inversa: np.linalg.inv()
- producto matricial: np.dot()
- diagonal: np.diag()
- inversa de una matriz: np.linalg.inv()



In [197]:
# Definir una matriz 2x3 con valores aleatorios entre 0 y 10
a = np.random.randint(0,10, size=(2,3))
print(a)


[[9 8 6]
 [2 0 9]]


In [198]:
# Definir una matriz 3x2 con valores aleatorios entre 0 y 10
b = np.random.randint(0,10, size=(3,2))
print(b)

[[7 8]
 [1 2]
 [2 7]]


### producto / multiplicación

Las operaciones basicas con arrays o matrices son "element wise".

Esto significa que se aplican a cada elemento de la matriz.

In [ ]:
print(a*b) #Esto va dá error porque va a tratar de hacer la operación element wise

Operaciones que no son element wise: dot y matmul o también @

In [200]:
# Para realizar la multiplicación matemática de matrices diferentes shapes:
# con la misma cantidad de elementos debemos usar la función 'dot' o 'matmul'
# En este caso el primer nº es (9*7 + 8*1 + 6*2).
# Daria un error si intentamos multiplicar matricez cuadradas del mismo tamaño

producto = np.dot(a,b)
print(producto)

[[ 83 130]
 [ 32  79]]


In [201]:
producto1 = np.matmul(a,b)
print(producto1)

[[ 83 130]
 [ 32  79]]


In [203]:
producto3 = a @ b
print(producto3)

[[ 83 130]
 [ 32  79]]


In [ ]:
c = np.random.randint(0,10, size=(3,2))
print(c)

#Error para imprimir dos matrices cuadradas
print(np.dot(b,c))

### Determinante de una matriz

In [211]:
print("Matriz:")
print(np.identity(3))
print("Determiante:")
print(np.linalg.det(a))


Matriz:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Determiante:
1.0


In [213]:
# Define una matriz de 3x3 con valores aleatorios entre 0 y 10
b = np.random.randint(0,10,size=(3,3))
print(b)

# Obtener el determiante de la matriz
print('Determiante:', np.linalg.det(b))


[[9 5 8]
 [9 6 6]
 [5 5 2]]
Determiante: 18.000000000000014


### Matriz inversa

In [235]:
# Matriz inversa
""" La matriz inversa de una matriz es igual a la matriz adjunta de su matriz transpuesta,
dividida por su determinante, siempre que este no sea cero"""



# Define una matriz de nº aleatorios entre 0 y 10 de tamaño 3x3
# Hashtag Programação
from numpy.random import default_rng

rng = default_rng()
c = rng.integers(9, size = (3,3))
print("matriz:\n", c)



#Obtener la matriz inversa
inversa = np.linalg.inv(c)
print("Matriz inversa:\n " ,inversa)



matriz:
 [[5 8 7]
 [4 6 1]
 [7 6 6]]
Matriz inversa:
  [[-0.26785714  0.05357143  0.30357143]
 [ 0.15178571  0.16964286 -0.20535714]
 [ 0.16071429 -0.23214286  0.01785714]]


### Matriz transpuesta

In [238]:
# Matriz transpuesta
""" La matriz transpuesta de una matriz es
 otra matriz que se obtiene al intercambiar las filas por las columnas"""

#Obtener una matriz aleatoria de 3x5
d= np.random.randint(0,10,size=(3,5))
print("matriz d:\n", d)


# Obtener la matriz transpuesta
print("transpuesta de d:\n",np.transpose(d))

matriz d:
 [[3 9 3 3 0]
 [3 3 0 0 7]
 [4 9 0 5 7]]
transpuesta de d:
 [[3 3 4]
 [9 3 9]
 [3 0 0]
 [3 0 5]
 [0 7 7]]


Más tipos de operaciones con arrays:
- **np.sum():** Suma de todos los elementos de un array
- **np.mean():** Media de todos los elementos de un array
- **np.std():** Desviación estándar de todos los elementos de un array
- **np.var():** Varianza de todos los elementos de un array
- **np.min():** Valor mínimo de todos los elementos de un array
- **np.max():** Valor máximo de todos los elementos de un array
- **np.argmin():** Indice del valor mínimo de un array
- **np.argmax():** Indice del valor máximo de un array
- **np.cumsum():** Sumatoria acumulada de un array
- **np.cumprod():** Producto acumulado de un array
- **np.flip():** Inversa de un array


### suma

In [241]:
# Define una matriz de nº aleatorios de 0 y 10 de tamaño 3x3

e = np.random.randint(0,10, size = (3,3))
print("matrix:\n", e)

# Obtener la suma de todos los elementos de la matriz
print("\ntotal:" ,np.sum(e))



matrix:
 [[0 5 8]
 [4 0 3]
 [6 4 1]]

total: 31


In [255]:
# Obtener el sumatorio de cada fila
print("Sumatorio  de cada fila:", np.sum(e,axis=1))

# Obtener el sumatorio de cada columna
print("Sumatorio  de cada fila:", np.sum(e,axis=0))

Sumatorio  de cada fila: [13  7 11]
Sumatorio  de cada fila: [10  9 12]


### mean()
media


In [242]:
# Obtener la media de la matriz
print("media", np.mean(e))

media 3.4444444444444446


### Maximo y minimo

In [243]:
# Obtener el valor maximo, el elemento mayor de la matriz
print("maximo:",np.max(e))
# Obtener el valor minimo, el elemento menor de la matriz
print("maximo:",np.min(e))


maximo: 8
maximo: 0


In [246]:
print(e)
# Obtener el valor maximo de cada fila (axe=1)
print("maximo de cada fila:", np.max(e, axis=1))

# Obtener el valor maximo de cada columna (axe=2)
print("Maximo de cada columnas:" ,np.max(e, axis=0))

[[0 5 8]
 [4 0 3]
 [6 4 1]]
maximo de cada fila: [8 4 6]
Maximo de cada columnas: [6 5 8]


In [254]:
# Obtener un unicoi valor maximo de una porción especifica
print(e[1:3,1:3])
print(np.max(e[1:3,1:3]))

[[0 3]
 [4 1]]
4


Ejercicios

In [ ]:
import numpy as np

mediana
https://brasilescola.uol.com.br/matematica/mediana.htm




In [ ]:
"""
Si tenemos total (size) de una matriz par, se calcula la media de dos valores centrales en orden crescente. ((a+b)/s):
ejemplo:
[3][5][6][8]
total de valores : 4 (par)
mediana = media de los valores centrales: 5+6/2

Si es impar el numero total, solo obtener el valor que está en el medio de la lista
[3][5][6]
total de valores = 3 (impar)
mediana = valor central: 5
"""

In [119]:
'''
Calcula la mediana de un array
'''
p = np.random.randint(3, size=(2,4,4))
print(p)
print("\nsuma()\n",sum(p))
print("\nnp.suma()",np.sum(p))
print("p.size:", p.size)

print("mediana", np.median(p))


[[[1 2 2 1]
  [2 2 0 2]
  [1 1 1 0]
  [0 2 1 0]]

 [[2 0 0 0]
  [2 2 0 0]
  [0 1 0 1]
  [0 0 0 2]]]

suma()
 [[3 2 2 1]
 [4 4 0 2]
 [1 2 1 1]
 [0 2 1 2]]

np.suma() 28
p.size: 32
mediana 1.0


In [117]:
'''
calcula la media de una matriz
'''
print("media ",(np.sum(p))/p.size)
print("\nmean()",np.mean(p))

media  0.9375

mean() 0.9375


### Reshape

In [260]:
# Va a coger una array de la dimension que sea y nos va a conformar con otro shape diferente

z = np.random.randint(0,10, size=(4,3))
print(z)

[[1 5 0]
 [2 7 3]
 [3 0 2]
 [1 6 6]]


In [263]:
z2 = z.reshape(6,2)
print(z2)

[[1 5]
 [0 2]
 [7 3]
 [3 0]
 [2 1]
 [6 6]]


### Ejemplo practico para reshape

In [278]:
""" Tengo un array de una linea y quiero transformar en una matriz"""

array_z = np.array([1,2,3,4,5,6,7,8,9,10,20,22,23,24,25])
print("size:",np.size(array_z), "\n")
print(array_z.reshape(3,5))
print("\notra manera con 3 dimensiones\n", array_z.reshape(3,1,5))



size: 15 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [20 22 23 24 25]]

otra manera con 3 dimensiones
 [[[ 1  2  3  4  5]]

 [[ 6  7  8  9 10]]

 [[20 22 23 24 25]]]
